#!/usr/bin/env bash
#in this script we learn about ping in port imcp

# Check if an argument is passed
if [ $# -eq 0 ]; then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
    exit 1
fi

ping -c 5 "$1"
